[theme]
base = "dark"

# General color setup
# Text Color (Soft, light violet)
textColor = "#E5E0FF"
# Primary Color (Vibrant Neon Magenta/Hot Pink)
primaryColor = "#FF00FF"
# Background Color (Dark, warm charcoal gray)
backgroundColor = "#1A1625"
# Secondary Background Color (Slightly lighter, warm dark gray for depth)
secondaryBackgroundColor = "#282233"

# Widgets
showWidgetBorder = true
# Border Color (Deep purple that ties the colors together)
borderColor = "#5A3A70"


# Base text
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]